### ISSUE TITLE
Small artefact on Aurora Store icon

### ISSUE THREAD

**Issue by AlbeyAmakiir** [JapanYoshi/dollphone-foss#79]
The icon for Aurora Store has a small line at the top left edge.
![IMG_20240321_124748](https://github.com/JapanYoshi/dollphone-foss/assets/2367996/b58def53-d9cc-481b-b704-3133ad3cb81f)

(Also, unless I'm getting "Aurora Store" confused with a different app, it seems to be called "Aurora Shop" in the Dollphone app and not automatically applying unlike other icons. But I'm not certain I'm not just missing something.)

**Comment by JapanYoshi** [comment]
This issue should be addressed in [this commit](https://github.com/JapanYoshi/dollphone-foss/commit/a7676b367e971bcede8a9e12162e0de545c888e8) and implemented in the next release.

**Comment by JapanYoshi** [comment]
![Screenshot_2024-04-04-18-23-56-65_61eb2106422858732c678213fd8da79f](https://github.com/JapanYoshi/dollphone-foss/assets/8707990/356b9044-24ee-46dd-8897-e08bd57e0683)
Screenshot from b11 (v1.1.1).
