### ISSUE TITLE
Fdroid missing latest update

### ISSUE THREAD

**Issue by AlbeyAmakiir** [JapanYoshi/dollphone-foss#88]
Fdroid seems to be missing v1.1.1. The latest on there is v1.1.0.

**Comment by JapanYoshi** [comment]
Fdroid updates the versions automatically by building the app on their end. It seems like 1.1.1 has an error that prevented their build from succeeding. This is an error that can’t be resolved until I deploy the next version.

2024年4月29日 21:55:34 JST、Albey Amakiir ***@***.***> より:

**Comment by JapanYoshi** [comment]
1.1.2 has been successfully built on F-droid! Closing.
